In [ ]:
# Project 8: Spam Message Detector

# Build a machine learning model that can classify a message as:
# Spam
# Ham (not spam)

# Covered:
# 1. dataset loading
# 2. text cleaning
# 3. label encoding
# 4. train-test split
# 5. text vectorization
# 6. model training
# 7. prediction
# 8. evaluation

In [ ]:
import pandas as pd
import numpy as np

import re                 #regular expression

from sklearn.model_selection  import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# STEP 2: CREATE A SMALL BEGINNER DATASET
# ---------------------------------------------------------

# We are creating the dataset manually so it can run directly in Colab
# label = spam or ham
# message = the text message

data = {
    "label": [
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam",
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam"
    ],
    "message": [
        "Hey, are we meeting today?",
        "Congratulations! You won a free iPhone. Click now!",
        "Please send me the notes of today class",
        "Win cash prize now by clicking this link",
        "Can you call me after lunch?",
        "Limited offer! Buy now and get 50 percent discount",
        "I am on the way to college",
        "You have been selected for a free vacation",
        "Let's study together in the evening",
        "Claim your lottery reward today",
        "Can you help me with Python homework?",
        "Urgent! Your account has won a huge reward",
        "Where are you now?",
        "Free entry in contest, click here now",
        "I will reach home by 8 PM",
        "Get a free gift voucher instantly",
        "Did you complete the assignment?",
        "Exclusive deal only for you, act fast",
        "Let's go for tea after class",
        "You are a lucky winner, claim your prize"
    ]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)
df

,label,message
0,ham,"Hey, are we meeting today?"
1,spam,Congratulations! You won a free iPhone. Click ...
2,ham,Please send me the notes of today class
3,spam,Win cash prize now by clicking this link
4,ham,Can you call me after lunch?
5,spam,Limited offer! Buy now and get 50 percent disc...
6,ham,I am on the way to college
7,spam,You have been selected for a free vacation
8,ham,Let's study together in the evening
9,spam,Claim your lottery reward today


In [ ]:
# Show first 5 rows
print("First 5 rows of dataset:")
display(df.head())

First 5 rows of dataset:


,label,message
0,ham,"Hey, are we meeting today?"
1,spam,Congratulations! You won a free iPhone. Click ...
2,ham,Please send me the notes of today class
3,spam,Win cash prize now by clicking this link
4,ham,Can you call me after lunch?


In [ ]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Info:")
df.info()

print("\nMissing Values:")
df.isnull().sum()


Dataset Shape:
(20, 2)

Column Names:
Index(['label', 'message'], dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    20 non-null     object
 1   message  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

Missing Values:


,0
label,0
message,0


In [ ]:
def clean_text(text):
  text=text.lower()
  text=re.sub(r'\d+','',text)
  text=re.sub(r'[^a-zA-Z\s]','',text)
  text=re.sub(r'\s+',' ',text).strip()

  return text

df["clean_message"]=df["message"].apply(clean_text)

print("\nDataset after text cleaning:")
print(df[["message","clean_message"]].head())


Dataset after text cleaning:
                                             message                                    clean_message
0                         Hey, are we meeting today?                         hey are we meeting today
1  Congratulations! You won a free iPhone. Click ...  congratulations you won a free iphone click now
2            Please send me the notes of today class          please send me the notes of today class
3           Win cash prize now by clicking this link         win cash prize now by clicking this link
4                       Can you call me after lunch?                      can you call me after lunch


In [ ]:
label_encoder=LabelEncoder()
df["label_encoded"]=label_encoder.fit_transform(df["label"])
print("\nOriginal and encoded datasets:")
print(df[["label","label_encoded"]].head())

print("Label Mapping:")
for i, class_name in enumerate(label_encoder.classes_):
  print(f"{class_name} --> {i}")


Original and encoded datasets:
  label  label_encoded
0   ham              0
1  spam              1
2   ham              0
3  spam              1
4   ham              0
Label Mapping:
ham --> 0
spam --> 1


In [ ]:
X=df["clean_message"]
y=df["label_encoded"]

print("Featured Sample: ")
print(X.head())
print("\nTarget Sample: ")
print(y.head())

Featured Sample: 
0                           hey are we meeting today
1    congratulations you won a free iphone click now
2            please send me the notes of today class
3           win cash prize now by clicking this link
4                        can you call me after lunch
Name: clean_message, dtype: object

Target Sample: 
0    0
1    1
2    0
3    1
4    0
Name: label_encoded, dtype: int64


In [57]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=38)
print("X_train: ",X_train.shape)
print("X_test: ",X_test.shape)
print("y_train: ",y_train.shape)
print("y_test: ",y_test.shape)

X_train:  (16,)
X_test:  (4,)
y_train:  (16,)
y_test:  (4,)


In [58]:
vectorizer= CountVectorizer()
X_train_vectorized=vectorizer.fit_transform(X_train)
X_test_vectorized=vectorizer.transform(X_test)

print("\nShape after vectorization: ")
print("X_train_vectorized: ",X_train_vectorized.shape)
print("X_test_vectorized: ",X_test_vectorized.shape)

print("\nSample Vocabulary Words: ")
print(list(vectorizer.vocabulary_.keys())[:10])



Shape after vectorization: 
X_train_vectorized:  (16, 71)
X_test_vectorized:  (4, 71)

Sample Vocabulary Words: 
['am', 'on', 'the', 'way', 'to', 'college', 'did', 'you', 'complete', 'assignment']


In [59]:
#Training Machine...

model=MultinomialNB()
model.fit(X_train_vectorized,y_train)

print("Model trained successfully!")

Model trained successfully!


In [60]:
y_pred=model.predict(X_test_vectorized)
print(y_pred)

print("\nActual Values:")
print(y_test.values)

[1 0 1 0]

Actual Values:
[0 0 1 0]


In [61]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of model: ")
print(accuracy)

print("\nClassification Report:")
print(classification_report(y_test,y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,y_pred))

Accuracy of model: 
0.75

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4


Confusion Matrix:
[[2 1]
 [0 1]]


In [65]:
new_messages=[
    "Congratulations! You won a free Bugatti!",
    "Can you send me the class link?",
    "Claim your prize now!",
    "I'll be home within 10 minutes.",
    "Exclusive offer today! Buy now!"
]

cleaned_new_messages=[clean_text(message) for message in new_messages]
new_messages_vectorized=vectorizer.transform(cleaned_new_messages)

new_predoctions=model.predict(new_messages_vectorized)

for message,prediction in zip(new_messages,new_predoctions):
  label_name=label_encoder.inverse_transform([prediction])[0]
  print(f"Message: {message}")
  print(f"Prediction: {label_name}\n")
  print("-"*50)

Message: Congratulations! You won a free Bugatti!
Prediction: spam

--------------------------------------------------
Message: Can you send me the class link?
Prediction: ham

--------------------------------------------------
Message: Claim your prize now!
Prediction: spam

--------------------------------------------------
Message: I'll be home within 10 minutes.
Prediction: spam

--------------------------------------------------
Message: Exclusive offer today! Buy now!
Prediction: spam

--------------------------------------------------
