In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
c=load_breast_cancer()

In [ ]:
a={
    "name":"Alice",
    "id":47001
}
a

{'name': 'Alice', 'id': 47001}

In [ ]:
c.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
c.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
c.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
c.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
df=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,output
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0.0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0.0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0.0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0.0


In [ ]:
df.shape

(569, 31)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

[]

In [ ]:
x=df.iloc[:,:-1]

In [ ]:
x.shape

(569, 30)

In [ ]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

,output
0,0.0
1,0.0
2,0.0
3,0.0
4,0.0
...,...
564,0.0
565,0.0
566,0.0
567,0.0


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)

In [ ]:
x_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
475,12.83,15.73,82.89,506.9,0.09040,0.08269,0.05835,0.03078,0.1705,0.05913,0.1499,0.4875,1.195,11.64,0.004873,0.01796,0.03318,0.008360,0.01601,0.002289,14.09,19.35,93.22,605.8,0.13260,0.2610,0.34760,0.09783,0.3006,0.07802
298,14.26,18.17,91.22,633.1,0.06576,0.05220,0.02475,0.01374,0.1635,0.05586,0.2300,0.6690,1.661,20.56,0.003169,0.01377,0.01079,0.005243,0.01103,0.001957,16.22,25.26,105.80,819.7,0.09445,0.2167,0.15650,0.07530,0.2636,0.07676
220,13.65,13.16,87.88,568.9,0.09646,0.08711,0.03888,0.02563,0.1360,0.06344,0.2102,0.4336,1.391,17.40,0.004133,0.01695,0.01652,0.006659,0.01371,0.002735,15.34,16.35,99.71,706.2,0.13110,0.2474,0.17590,0.08056,0.2380,0.08718
549,10.82,24.21,68.89,361.6,0.08192,0.06602,0.01548,0.00816,0.1976,0.06328,0.5196,1.9180,3.564,33.00,0.008263,0.01870,0.01277,0.005917,0.02466,0.002977,13.03,31.45,83.90,505.6,0.12040,0.1633,0.06194,0.03264,0.3059,0.07626
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.016640,0.02324,0.006185,25.74,39.42,184.60,1821.0,0.16500,0.8681,0.93870,0.26500,0.4087,0.12400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,11.62,18.18,76.38,408.8,0.11750,0.14830,0.10200,0.05564,0.1957,0.07255,0.4101,1.7400,3.027,27.85,0.014590,0.03206,0.04961,0.018410,0.01807,0.005217,13.36,25.40,88.14,528.1,0.17800,0.2878,0.31860,0.14160,0.2660,0.09270
407,12.85,21.37,82.63,514.5,0.07551,0.08316,0.06126,0.01867,0.1580,0.06114,0.4993,1.7980,2.552,41.24,0.006011,0.04480,0.05175,0.013410,0.02669,0.007731,14.40,27.01,91.63,645.8,0.09402,0.1936,0.18380,0.05601,0.2488,0.08151
243,13.75,23.77,88.54,590.0,0.08043,0.06807,0.04697,0.02344,0.1773,0.05429,0.4347,1.0570,2.829,39.93,0.004351,0.02667,0.03371,0.010070,0.02598,0.003087,15.01,26.34,98.00,706.0,0.09368,0.1442,0.13590,0.06106,0.2663,0.06321
321,20.16,19.66,131.10,1274.0,0.08020,0.08564,0.11550,0.07726,0.1928,0.05096,0.5925,0.6863,3.868,74.85,0.004536,0.01376,0.02645,0.012470,0.02193,0.001589,23.06,23.03,150.20,1657.0,0.10540,0.1537,0.26060,0.14250,0.3055,0.05933


In [ ]:
x_train.shape

(455, 30)

In [ ]:
y_train.shape

(455,)

In [ ]:
x_test.shape

(114, 30)

In [ ]:
y_test.shape

(114,)

In [ ]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [ ]:
std=StandardScaler()
mm=MinMaxScaler()

In [ ]:
x_train_std_sc_data=std.fit_transform(x_train)
x_train_std_sc_data

array([[-0.36498729, -0.83463794, -0.37044213, ..., -0.25967334,
         0.17192889, -0.3532633 ],
       [ 0.05208811, -0.26700868, -0.01772895, ..., -0.60430302,
        -0.44112743, -0.4234167 ],
       [-0.12582517, -1.43250975, -0.15915297, ..., -0.52384354,
        -0.86529613,  0.15674078],
       ...,
       [-0.09665906,  1.03574702, -0.1312069 , ..., -0.82212489,
        -0.39639089, -1.17784414],
       [ 1.77288871,  0.07961739,  1.6708907 , ...,  0.4236204 ,
         0.25311743, -1.39387207],
       [-0.76747963,  0.38436917, -0.75491221, ..., -0.81891263,
        -0.2323569 ,  0.23079159]])

In [ ]:
employees = {
  "emp_id": [12000, 12001, 12002, 12003, 12004, 12005, 12006, 12007, 12008, 12009],
  "emp_name": ["Sara", "Laura", "Bryan", "John", "Maria", "David", "Emily", "Michael", "Jessica", "Daniel"],
  "salary": [60000, 75000, 50000, 90000, 62000, 80000, 58000, 70000, 65000, 85000],
  "feedback": [
    "Excellent team player.",
    "Consistently meets targets.",
    "Needs to improve communication skills.",
    "Highly innovative and proactive.",
    "Good analytical skills.",
    "Strong leadership potential.",
    "Reliable and detail-oriented.",
    "Problem-solver, but sometimes slow.",
    "Collaborative and supportive.",
    "Exceptional technical skills."
  ]
}

In [ ]:
df1=pd.DataFrame(employees)
df1

,emp_id,emp_name,salary,feedback
0,12000,Sara,60000,Excellent team player.
1,12001,Laura,75000,Consistently meets targets.
2,12002,Bryan,50000,Needs to improve communication skills.
3,12003,John,90000,Highly innovative and proactive.
4,12004,Maria,62000,Good analytical skills.
5,12005,David,80000,Strong leadership potential.
6,12006,Emily,58000,Reliable and detail-oriented.
7,12007,Michael,70000,"Problem-solver, but sometimes slow."
8,12008,Jessica,65000,Collaborative and supportive.
9,12009,Daniel,85000,Exceptional technical skills.


In [ ]:
df1["emp_name"].value_counts()

,count
emp_name,
Sara,1
Laura,1
Bryan,1
John,1
Maria,1
David,1
Emily,1
Michael,1
Jessica,1


In [ ]:
df1["feedback"].value_counts()

,count
feedback,
Excellent team player.,1
Consistently meets targets.,1
Needs to improve communication skills.,1
Highly innovative and proactive.,1
Good analytical skills.,1
Strong leadership potential.,1
Reliable and detail-oriented.,1
"Problem-solver, but sometimes slow.",1
Collaborative and supportive.,1


In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
One=OneHotEncoder(sparse_output=False)
L=LabelEncoder()

In [ ]:
df1['feedback']=L.fit_transform(df1['feedback'])
df1

,emp_id,emp_name,salary,feedback
0,12000,Sara,60000,2
1,12001,Laura,75000,1
2,12002,Bryan,50000,6
3,12003,John,90000,5
4,12004,Maria,62000,4
5,12005,David,80000,9
6,12006,Emily,58000,8
7,12007,Michael,70000,7
8,12008,Jessica,65000,0
9,12009,Daniel,85000,3


In [ ]:
a=One.fit_transform(df1[["emp_name"]])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
df1_enc=pd.DataFrame(a,columns=One.get_feature_names_out())
df1_enc

,emp_name_Bryan,emp_name_Daniel,emp_name_David,emp_name_Emily,emp_name_Jessica,emp_name_John,emp_name_Laura,emp_name_Maria,emp_name_Michael,emp_name_Sara
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
df1_new=pd.concat([df1,df1_enc],axis=1)

In [ ]:
df1_new

,emp_id,emp_name,salary,feedback,emp_name_Bryan,emp_name_Daniel,emp_name_David,emp_name_Emily,emp_name_Jessica,emp_name_John,emp_name_Laura,emp_name_Maria,emp_name_Michael,emp_name_Sara
0,12000,Sara,60000,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12001,Laura,75000,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,12002,Bryan,50000,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,12003,John,90000,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,12004,Maria,62000,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,12005,David,80000,9,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,12006,Emily,58000,8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,12007,Michael,70000,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,12008,Jessica,65000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,12009,Daniel,85000,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
df1_new.drop("emp_name",axis=1,inplace=True)
df1_new

,emp_id,salary,feedback,emp_name_Bryan,emp_name_Daniel,emp_name_David,emp_name_Emily,emp_name_Jessica,emp_name_John,emp_name_Laura,emp_name_Maria,emp_name_Michael,emp_name_Sara
0,12000,60000,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12001,75000,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,12002,50000,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,12003,90000,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,12004,62000,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,12005,80000,9,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,12006,58000,8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,12007,70000,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,12008,65000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,12009,85000,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
